Clean architecture API big data
jabardigitalservice/pikobar-isoman-backend pull request #3
Opened 2021-07-27 05:04 UTC by rizkyrmsyah

## Overview
implement clean architecture in API Big data

2021-07-27 08:02 UTC, yohang88 requested changes
Great! Good job @rizkyrmsyah for implementing improvement for clean architecture. There are 3 minors issue, please kindly checks 😁

2021-07-27 08:02 UTC, yohang88 commented on bigdata-service/src/transport/http/tracking_handler.go
> +		c.JSON(http.StatusUnprocessableEntity, gin.H{
Generally, if no result available, HTTP response code should 404 Not Found.

2021-07-27 08:27 UTC, rizkyrmsyah commented on bigdata-service/src/config/config.go
> +var configFilename = "../.env"
.env file is required, if .env file is not exists service can't work and throw an error

2021-07-27 08:31 UTC, rizkyrmsyah commented on bigdata-service/src/transport/http/tracking_handler.go
> +		c.JSON(http.StatusUnprocessableEntity, gin.H{
sure.. i forgot to change this :D

2021-07-27 08:57 UTC, firmanJS approved these changes

2021-07-27 12:42 UTC, yohang88 commented on bigdata-service/src/config/config.go
> +var configFilename = "../.env"
In first initial setup, we can start server without .env file 😛  

.env file should not mandatory (for development only). Because in staging/production server, our configre rely on environment variables (injected by operating system).

https://12factor.net/config

2021-07-28 00:29 UTC, rizkyrmsyah commented on bigdata-service/src/config/config.go
> +var configFilename = "../.env"
ahh i see, okay fixed 😄

2021-07-28 02:31 UTC, rizkyrmsyah commented on bigdata-service/src/config/config.go
> +var configFilename = "../.env"
[](https://github.com/jabardigitalservice/pikobar-isoman-backend/pull/3/commits/73cd9bdd03fb548fd43d265176c1fee6ab5ed2ba)

2021-07-28 04:36 UTC, yohang88 approved these changes

2021-07-28 04:36 UTC, merged